name: NCJD - 自动化构建与部署流程

# 当推送到 main 分支时自动触发
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # 使用最新的Ubuntu运行环境
    runs-on: ubuntu-latest

    steps:
      - name: 1. 复制我的仓库到虚拟机
        uses: actions/checkout@v4

      - name: 2. 配置Java环境（JDK 17）
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven # 开启 Maven 缓存以加快速度

      - name: 3. 使用Maven构建项目（跳过测试以加快速度）
        run: mvn clean package -DskipTests

      - name: 4. 构建Docker镜像
        run: docker build -t ncjd:latest .

      - name: 5 登录到Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: 6. 推送镜像
        run: |
          docker tag ncjd:latest ahornbeast/ncjd:latest
          docker push ahornbeast/ncjd:latest
          
######## 在服务器端执行命令：拉取镜像 ##########
# 开启代理 (Docker不会读取全局代理)：/etc/systemd/system/docker.service.d/http-proxy.conf 
# systemctl daemon-reload
# systemctl restart docker
# systemctl show docker --property Environment
# netstat -tlnp | grep 1081

# 本机ssh代理
# ssh -R 1081:localhost:6666 root@47.116.37.204 -N
# curl -x http://127.0.0.1:1081 https://www.google.com -v

# 拉取镜像
#  docker pull ahornbeast/ncjd:latest
#  docker stop ncjd || true
#  docker rm ncjd || true
#  docker run -d -p 8080:8080 --name ncjd ahornbeast/ncjd:latest